course='I am a honest person'
print(len(course))
print(course.upper())
print(course.lower())
print(course.find('h'))
print(course.find('a'))
print(course.find('honest'))
print(course.replace('honest',"honest and good"))
print(course.replace('h','j'))
print('person' in course)
